kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maven-nexus3
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: maven-nexus3
