apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-nexus3
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /data/maven-nexus3
    server: 10.0.11.94
  storageClassName: maven-nexus3
