kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-redis
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: gitlab-redis
