apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-postgresql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /data/gitlab-postgresql
    server: 10.0.11.94
  storageClassName: gitlab-postgresql
