kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins
  namespace: op
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: jenkins
